//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ewininfo.com", ConfigurationName="ServiceReference1.DeviceFailureService")]
    public interface DeviceFailureService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference1.addDeviceAndonInfoResponse addDeviceAndonInfo(ServiceReference1.addDeviceAndonInfo request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference1.queryDeviceFailureListResponse queryDeviceFailureList(ServiceReference1.queryDeviceFailureList request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceAndonInfo", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addDeviceAndonInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deviceNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string failureNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userNo;
        
        public addDeviceAndonInfo() {
        }
        
        public addDeviceAndonInfo(string deviceNo, string failureNo, string userNo) {
            this.deviceNo = deviceNo;
            this.failureNo = failureNo;
            this.userNo = userNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceAndonInfoResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addDeviceAndonInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addDeviceAndonInfoResponse() {
        }
        
        public addDeviceAndonInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ewininfo.com")]
    public partial class deviceFailureInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string failureNoField;
        
        private string failureNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string failureNo {
            get {
                return this.failureNoField;
            }
            set {
                this.failureNoField = value;
                this.RaisePropertyChanged("failureNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string failureName {
            get {
                return this.failureNameField;
            }
            set {
                this.failureNameField = value;
                this.RaisePropertyChanged("failureName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryDeviceFailureList", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryDeviceFailureList {
        
        public queryDeviceFailureList() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryDeviceFailureListResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryDeviceFailureListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.deviceFailureInfo[] @return;
        
        public queryDeviceFailureListResponse() {
        }
        
        public queryDeviceFailureListResponse(ServiceReference1.deviceFailureInfo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceFailureServiceChannel : ServiceReference1.DeviceFailureService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceFailureServiceClient : System.ServiceModel.ClientBase<ServiceReference1.DeviceFailureService>, ServiceReference1.DeviceFailureService {
        
        public DeviceFailureServiceClient() {
        }
        
        public DeviceFailureServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceFailureServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceFailureServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceFailureServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.addDeviceAndonInfoResponse ServiceReference1.DeviceFailureService.addDeviceAndonInfo(ServiceReference1.addDeviceAndonInfo request) {
            return base.Channel.addDeviceAndonInfo(request);
        }
        
        public string addDeviceAndonInfo(string deviceNo, string failureNo, string userNo) {
            ServiceReference1.addDeviceAndonInfo inValue = new ServiceReference1.addDeviceAndonInfo();
            inValue.deviceNo = deviceNo;
            inValue.failureNo = failureNo;
            inValue.userNo = userNo;
            ServiceReference1.addDeviceAndonInfoResponse retVal = ((ServiceReference1.DeviceFailureService)(this)).addDeviceAndonInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.queryDeviceFailureListResponse ServiceReference1.DeviceFailureService.queryDeviceFailureList(ServiceReference1.queryDeviceFailureList request) {
            return base.Channel.queryDeviceFailureList(request);
        }
        
        public ServiceReference1.deviceFailureInfo[] queryDeviceFailureList() {
            ServiceReference1.queryDeviceFailureList inValue = new ServiceReference1.queryDeviceFailureList();
            ServiceReference1.queryDeviceFailureListResponse retVal = ((ServiceReference1.DeviceFailureService)(this)).queryDeviceFailureList(inValue);
            return retVal.@return;
        }
    }
}
