//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ewininfo.com", ConfigurationName="ServiceReference3.DeviceStatusService")]
    public interface DeviceStatusService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference3.addDeviceStatusHistoryResponse addDeviceStatusHistory(ServiceReference3.addDeviceStatusHistory request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference3.addDeviceStatusCurrentResponse addDeviceStatusCurrent(ServiceReference3.addDeviceStatusCurrent request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ewininfo.com")]
    public partial class deviceStatusInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dispatchOrderNoField;
        
        private string deviceNoField;
        
        private long workTimeField;
        
        private long prdBeatField;
        
        private long energyConsumptionField;
        
        private long standbyTimeField;
        
        private long powerField;
        
        private long deviceCollectNumField;
        
        private long speedField;
        
        private long pressureField;
        
        private long prepareTimeField;
        
        private long realWorkTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispatchOrderNo {
            get {
                return this.dispatchOrderNoField;
            }
            set {
                this.dispatchOrderNoField = value;
                this.RaisePropertyChanged("dispatchOrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deviceNo {
            get {
                return this.deviceNoField;
            }
            set {
                this.deviceNoField = value;
                this.RaisePropertyChanged("deviceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long workTime {
            get {
                return this.workTimeField;
            }
            set {
                this.workTimeField = value;
                this.RaisePropertyChanged("workTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long prdBeat {
            get {
                return this.prdBeatField;
            }
            set {
                this.prdBeatField = value;
                this.RaisePropertyChanged("prdBeat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long energyConsumption {
            get {
                return this.energyConsumptionField;
            }
            set {
                this.energyConsumptionField = value;
                this.RaisePropertyChanged("energyConsumption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long standbyTime {
            get {
                return this.standbyTimeField;
            }
            set {
                this.standbyTimeField = value;
                this.RaisePropertyChanged("standbyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long power {
            get {
                return this.powerField;
            }
            set {
                this.powerField = value;
                this.RaisePropertyChanged("power");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long deviceCollectNum {
            get {
                return this.deviceCollectNumField;
            }
            set {
                this.deviceCollectNumField = value;
                this.RaisePropertyChanged("deviceCollectNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
                this.RaisePropertyChanged("speed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long pressure {
            get {
                return this.pressureField;
            }
            set {
                this.pressureField = value;
                this.RaisePropertyChanged("pressure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long prepareTime {
            get {
                return this.prepareTimeField;
            }
            set {
                this.prepareTimeField = value;
                this.RaisePropertyChanged("prepareTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long realWorkTime {
            get {
                return this.realWorkTimeField;
            }
            set {
                this.realWorkTimeField = value;
                this.RaisePropertyChanged("realWorkTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceStatusHistory", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addDeviceStatusHistory {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference3.deviceStatusInfo data;
        
        public addDeviceStatusHistory() {
        }
        
        public addDeviceStatusHistory(ServiceReference3.deviceStatusInfo data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceStatusHistoryResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addDeviceStatusHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addDeviceStatusHistoryResponse() {
        }
        
        public addDeviceStatusHistoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceStatusCurrent", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addDeviceStatusCurrent {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference3.deviceStatusInfo data;
        
        public addDeviceStatusCurrent() {
        }
        
        public addDeviceStatusCurrent(ServiceReference3.deviceStatusInfo data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addDeviceStatusCurrentResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addDeviceStatusCurrentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addDeviceStatusCurrentResponse() {
        }
        
        public addDeviceStatusCurrentResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceStatusServiceChannel : ServiceReference3.DeviceStatusService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeviceStatusServiceClient : System.ServiceModel.ClientBase<ServiceReference3.DeviceStatusService>, ServiceReference3.DeviceStatusService {
        
        public DeviceStatusServiceClient() {
        }
        
        public DeviceStatusServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeviceStatusServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceStatusServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeviceStatusServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.addDeviceStatusHistoryResponse ServiceReference3.DeviceStatusService.addDeviceStatusHistory(ServiceReference3.addDeviceStatusHistory request) {
            return base.Channel.addDeviceStatusHistory(request);
        }
        
        public string addDeviceStatusHistory(ServiceReference3.deviceStatusInfo data) {
            ServiceReference3.addDeviceStatusHistory inValue = new ServiceReference3.addDeviceStatusHistory();
            inValue.data = data;
            ServiceReference3.addDeviceStatusHistoryResponse retVal = ((ServiceReference3.DeviceStatusService)(this)).addDeviceStatusHistory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference3.addDeviceStatusCurrentResponse ServiceReference3.DeviceStatusService.addDeviceStatusCurrent(ServiceReference3.addDeviceStatusCurrent request) {
            return base.Channel.addDeviceStatusCurrent(request);
        }
        
        public string addDeviceStatusCurrent(ServiceReference3.deviceStatusInfo data) {
            ServiceReference3.addDeviceStatusCurrent inValue = new ServiceReference3.addDeviceStatusCurrent();
            inValue.data = data;
            ServiceReference3.addDeviceStatusCurrentResponse retVal = ((ServiceReference3.DeviceStatusService)(this)).addDeviceStatusCurrent(inValue);
            return retVal.@return;
        }
    }
}
