//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ewininfo.com", ConfigurationName="ServiceReference5.ChkItemListService")]
    public interface ChkItemListService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference5.queryChkItemByDispatchNoResponse queryChkItemByDispatchNo(ServiceReference5.queryChkItemByDispatchNo request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference5.addTwProductProcessCheckResponse addTwProductProcessCheck(ServiceReference5.addTwProductProcessCheck request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ewininfo.com")]
    public partial class ReturnChkItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string dispatchNoField;
        
        private string checkItemField;
        
        private string checkReqField;
        
        private string lowerToleranceLimitField;
        
        private string lowerControlLimitField;
        
        private string toleranceLimitField;
        
        private string upperControlLimitField;
        
        private string checkResultField;
        
        private string judgeResultField;
        
        private string productNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispatchNo {
            get {
                return this.dispatchNoField;
            }
            set {
                this.dispatchNoField = value;
                this.RaisePropertyChanged("dispatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string checkItem {
            get {
                return this.checkItemField;
            }
            set {
                this.checkItemField = value;
                this.RaisePropertyChanged("checkItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string checkReq {
            get {
                return this.checkReqField;
            }
            set {
                this.checkReqField = value;
                this.RaisePropertyChanged("checkReq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lowerToleranceLimit {
            get {
                return this.lowerToleranceLimitField;
            }
            set {
                this.lowerToleranceLimitField = value;
                this.RaisePropertyChanged("lowerToleranceLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lowerControlLimit {
            get {
                return this.lowerControlLimitField;
            }
            set {
                this.lowerControlLimitField = value;
                this.RaisePropertyChanged("lowerControlLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toleranceLimit {
            get {
                return this.toleranceLimitField;
            }
            set {
                this.toleranceLimitField = value;
                this.RaisePropertyChanged("toleranceLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string upperControlLimit {
            get {
                return this.upperControlLimitField;
            }
            set {
                this.upperControlLimitField = value;
                this.RaisePropertyChanged("upperControlLimit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string checkResult {
            get {
                return this.checkResultField;
            }
            set {
                this.checkResultField = value;
                this.RaisePropertyChanged("checkResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string judgeResult {
            get {
                return this.judgeResultField;
            }
            set {
                this.judgeResultField = value;
                this.RaisePropertyChanged("judgeResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productNum {
            get {
                return this.productNumField;
            }
            set {
                this.productNumField = value;
                this.RaisePropertyChanged("productNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryChkItemByDispatchNo", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryChkItemByDispatchNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dispatchNo;
        
        public queryChkItemByDispatchNo() {
        }
        
        public queryChkItemByDispatchNo(string dispatchNo) {
            this.dispatchNo = dispatchNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryChkItemByDispatchNoResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryChkItemByDispatchNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference5.ReturnChkItem[] @return;
        
        public queryChkItemByDispatchNoResponse() {
        }
        
        public queryChkItemByDispatchNoResponse(ServiceReference5.ReturnChkItem[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTwProductProcessCheck", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addTwProductProcessCheck {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference5.ReturnChkItem[] data;
        
        public addTwProductProcessCheck() {
        }
        
        public addTwProductProcessCheck(ServiceReference5.ReturnChkItem[] data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addTwProductProcessCheckResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addTwProductProcessCheckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addTwProductProcessCheckResponse() {
        }
        
        public addTwProductProcessCheckResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChkItemListServiceChannel : ServiceReference5.ChkItemListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChkItemListServiceClient : System.ServiceModel.ClientBase<ServiceReference5.ChkItemListService>, ServiceReference5.ChkItemListService {
        
        public ChkItemListServiceClient() {
        }
        
        public ChkItemListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChkItemListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChkItemListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChkItemListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.queryChkItemByDispatchNoResponse ServiceReference5.ChkItemListService.queryChkItemByDispatchNo(ServiceReference5.queryChkItemByDispatchNo request) {
            return base.Channel.queryChkItemByDispatchNo(request);
        }
        
        public ServiceReference5.ReturnChkItem[] queryChkItemByDispatchNo(string dispatchNo) {
            ServiceReference5.queryChkItemByDispatchNo inValue = new ServiceReference5.queryChkItemByDispatchNo();
            inValue.dispatchNo = dispatchNo;
            ServiceReference5.queryChkItemByDispatchNoResponse retVal = ((ServiceReference5.ChkItemListService)(this)).queryChkItemByDispatchNo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference5.addTwProductProcessCheckResponse ServiceReference5.ChkItemListService.addTwProductProcessCheck(ServiceReference5.addTwProductProcessCheck request) {
            return base.Channel.addTwProductProcessCheck(request);
        }
        
        public string addTwProductProcessCheck(ServiceReference5.ReturnChkItem[] data) {
            ServiceReference5.addTwProductProcessCheck inValue = new ServiceReference5.addTwProductProcessCheck();
            inValue.data = data;
            ServiceReference5.addTwProductProcessCheckResponse retVal = ((ServiceReference5.ChkItemListService)(this)).addTwProductProcessCheck(inValue);
            return retVal.@return;
        }
    }
}
