//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference7 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ewininfo.com", ConfigurationName="ServiceReference7.MaterialAndonService")]
    public interface MaterialAndonService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference7.addMaterialAndonInfoResponse addMaterialAndonInfo(ServiceReference7.addMaterialAndonInfo request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference7.queryActiveMaterialResponse queryActiveMaterial(ServiceReference7.queryActiveMaterial request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMaterialAndonInfo", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addMaterialAndonInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dispatchNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        public addMaterialAndonInfo() {
        }
        
        public addMaterialAndonInfo(string dispatchNo, string userId) {
            this.dispatchNo = dispatchNo;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMaterialAndonInfoResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addMaterialAndonInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addMaterialAndonInfoResponse() {
        }
        
        public addMaterialAndonInfoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ewininfo.com")]
    public partial class ReturnMaterialInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dispatchOrderNoField;
        
        private string batchNoField;
        
        private string deviceNoField;
        
        private long planNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispatchOrderNo {
            get {
                return this.dispatchOrderNoField;
            }
            set {
                this.dispatchOrderNoField = value;
                this.RaisePropertyChanged("dispatchOrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string batchNo {
            get {
                return this.batchNoField;
            }
            set {
                this.batchNoField = value;
                this.RaisePropertyChanged("batchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string deviceNo {
            get {
                return this.deviceNoField;
            }
            set {
                this.deviceNoField = value;
                this.RaisePropertyChanged("deviceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long planNum {
            get {
                return this.planNumField;
            }
            set {
                this.planNumField = value;
                this.RaisePropertyChanged("planNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryActiveMaterial", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryActiveMaterial {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deviceNo;
        
        public queryActiveMaterial() {
        }
        
        public queryActiveMaterial(string deviceNo) {
            this.deviceNo = deviceNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryActiveMaterialResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryActiveMaterialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference7.ReturnMaterialInfo[] @return;
        
        public queryActiveMaterialResponse() {
        }
        
        public queryActiveMaterialResponse(ServiceReference7.ReturnMaterialInfo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaterialAndonServiceChannel : ServiceReference7.MaterialAndonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialAndonServiceClient : System.ServiceModel.ClientBase<ServiceReference7.MaterialAndonService>, ServiceReference7.MaterialAndonService {
        
        public MaterialAndonServiceClient() {
        }
        
        public MaterialAndonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialAndonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialAndonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialAndonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference7.addMaterialAndonInfoResponse ServiceReference7.MaterialAndonService.addMaterialAndonInfo(ServiceReference7.addMaterialAndonInfo request) {
            return base.Channel.addMaterialAndonInfo(request);
        }
        
        public string addMaterialAndonInfo(string dispatchNo, string userId) {
            ServiceReference7.addMaterialAndonInfo inValue = new ServiceReference7.addMaterialAndonInfo();
            inValue.dispatchNo = dispatchNo;
            inValue.userId = userId;
            ServiceReference7.addMaterialAndonInfoResponse retVal = ((ServiceReference7.MaterialAndonService)(this)).addMaterialAndonInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference7.queryActiveMaterialResponse ServiceReference7.MaterialAndonService.queryActiveMaterial(ServiceReference7.queryActiveMaterial request) {
            return base.Channel.queryActiveMaterial(request);
        }
        
        public ServiceReference7.ReturnMaterialInfo[] queryActiveMaterial(string deviceNo) {
            ServiceReference7.queryActiveMaterial inValue = new ServiceReference7.queryActiveMaterial();
            inValue.deviceNo = deviceNo;
            ServiceReference7.queryActiveMaterialResponse retVal = ((ServiceReference7.MaterialAndonService)(this)).queryActiveMaterial(inValue);
            return retVal.@return;
        }
    }
}
