//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ewininfo.com", ConfigurationName="ServiceReference2.ActiveDispatchOrderService")]
    public interface ActiveDispatchOrderService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference2.queryActiveDispatchOrderResponse queryActiveDispatchOrder(ServiceReference2.queryActiveDispatchOrder request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ServiceReference2.addActiveDispatchResponse addActiveDispatch(ServiceReference2.addActiveDispatch request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ewininfo.com")]
    public partial class ReturnActiveDispatch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long dispatchIdField;
        
        private bool dispatchIdFieldSpecified;
        
        private string dispatchNoField;
        
        private string planStartTimeField;
        
        private string planEndTimeField;
        
        private string productNoField;
        
        private string productNameField;
        
        private string operationUserField;
        
        private string planNumField;
        
        private string qualifiedNumField;
        
        private string disqualifiedNumField;
        
        private string currentProcessField;
        
        private string startDateField;
        
        private string entireLifeCountField;
        
        private string useNumberField;
        
        private string singleFactorField;
        
        private string materialBatchNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long dispatchId {
            get {
                return this.dispatchIdField;
            }
            set {
                this.dispatchIdField = value;
                this.RaisePropertyChanged("dispatchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dispatchIdSpecified {
            get {
                return this.dispatchIdFieldSpecified;
            }
            set {
                this.dispatchIdFieldSpecified = value;
                this.RaisePropertyChanged("dispatchIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dispatchNo {
            get {
                return this.dispatchNoField;
            }
            set {
                this.dispatchNoField = value;
                this.RaisePropertyChanged("dispatchNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string planStartTime {
            get {
                return this.planStartTimeField;
            }
            set {
                this.planStartTimeField = value;
                this.RaisePropertyChanged("planStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string planEndTime {
            get {
                return this.planEndTimeField;
            }
            set {
                this.planEndTimeField = value;
                this.RaisePropertyChanged("planEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productNo {
            get {
                return this.productNoField;
            }
            set {
                this.productNoField = value;
                this.RaisePropertyChanged("productNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
                this.RaisePropertyChanged("productName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string operationUser {
            get {
                return this.operationUserField;
            }
            set {
                this.operationUserField = value;
                this.RaisePropertyChanged("operationUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string planNum {
            get {
                return this.planNumField;
            }
            set {
                this.planNumField = value;
                this.RaisePropertyChanged("planNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string qualifiedNum {
            get {
                return this.qualifiedNumField;
            }
            set {
                this.qualifiedNumField = value;
                this.RaisePropertyChanged("qualifiedNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string disqualifiedNum {
            get {
                return this.disqualifiedNumField;
            }
            set {
                this.disqualifiedNumField = value;
                this.RaisePropertyChanged("disqualifiedNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currentProcess {
            get {
                return this.currentProcessField;
            }
            set {
                this.currentProcessField = value;
                this.RaisePropertyChanged("currentProcess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string entireLifeCount {
            get {
                return this.entireLifeCountField;
            }
            set {
                this.entireLifeCountField = value;
                this.RaisePropertyChanged("entireLifeCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string useNumber {
            get {
                return this.useNumberField;
            }
            set {
                this.useNumberField = value;
                this.RaisePropertyChanged("useNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string singleFactor {
            get {
                return this.singleFactorField;
            }
            set {
                this.singleFactorField = value;
                this.RaisePropertyChanged("singleFactor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string materialBatchNo {
            get {
                return this.materialBatchNoField;
            }
            set {
                this.materialBatchNoField = value;
                this.RaisePropertyChanged("materialBatchNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryActiveDispatchOrder", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryActiveDispatchOrder {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deviceNo;
        
        public queryActiveDispatchOrder() {
        }
        
        public queryActiveDispatchOrder(string deviceNo) {
            this.deviceNo = deviceNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryActiveDispatchOrderResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class queryActiveDispatchOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference2.ReturnActiveDispatch[] @return;
        
        public queryActiveDispatchOrderResponse() {
        }
        
        public queryActiveDispatchOrderResponse(ServiceReference2.ReturnActiveDispatch[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addActiveDispatch", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addActiveDispatch {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference2.ReturnActiveDispatch data;
        
        public addActiveDispatch() {
        }
        
        public addActiveDispatch(ServiceReference2.ReturnActiveDispatch data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addActiveDispatchResponse", WrapperNamespace="http://www.ewininfo.com", IsWrapped=true)]
    public partial class addActiveDispatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ewininfo.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addActiveDispatchResponse() {
        }
        
        public addActiveDispatchResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActiveDispatchOrderServiceChannel : ServiceReference2.ActiveDispatchOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActiveDispatchOrderServiceClient : System.ServiceModel.ClientBase<ServiceReference2.ActiveDispatchOrderService>, ServiceReference2.ActiveDispatchOrderService {
        
        public ActiveDispatchOrderServiceClient() {
        }
        
        public ActiveDispatchOrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActiveDispatchOrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDispatchOrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActiveDispatchOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference2.queryActiveDispatchOrderResponse ServiceReference2.ActiveDispatchOrderService.queryActiveDispatchOrder(ServiceReference2.queryActiveDispatchOrder request) {
            return base.Channel.queryActiveDispatchOrder(request);
        }
        
        public ServiceReference2.ReturnActiveDispatch[] queryActiveDispatchOrder(string deviceNo) {
            ServiceReference2.queryActiveDispatchOrder inValue = new ServiceReference2.queryActiveDispatchOrder();
            inValue.deviceNo = deviceNo;
            ServiceReference2.queryActiveDispatchOrderResponse retVal = ((ServiceReference2.ActiveDispatchOrderService)(this)).queryActiveDispatchOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference2.addActiveDispatchResponse ServiceReference2.ActiveDispatchOrderService.addActiveDispatch(ServiceReference2.addActiveDispatch request) {
            return base.Channel.addActiveDispatch(request);
        }
        
        public string addActiveDispatch(ServiceReference2.ReturnActiveDispatch data) {
            ServiceReference2.addActiveDispatch inValue = new ServiceReference2.addActiveDispatch();
            inValue.data = data;
            ServiceReference2.addActiveDispatchResponse retVal = ((ServiceReference2.ActiveDispatchOrderService)(this)).addActiveDispatch(inValue);
            return retVal.@return;
        }
    }
}
